name: Deployment Excersise 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Install eslint
        run: npm install eslint
      - name: Run linter
        run: npm run lint
      - name: Install vitest
        run: npm install vitest
      - name: Run tests
        run: npm run test
      - name: Install vite
        run: npm install vite
      - name: Run build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
